blog/urls.py
from . import views
from django.urls import include

from django.urls import path
from .feeds import LatestPostsFeed, AtomSiteNewsFeed

urlpatterns = [
    path("feed/rss", LatestPostsFeed(), name="post_feed"),
    path("feed/atom", AtomSiteNewsFeed()),
    path('about', views.AboutView.as_view(), name='about'),
    path('contact', views.ContactView, name='contact'),
    path("", views.PostList.as_view(), name="home"),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls"), name="blog-urls"),
    path("summernote/", include("django_summernote.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("post_detail", kwargs={"slug": str(self.slug)})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

blog/forms.py
from .models import Comment
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets ={
            'body' : SummernoteWidget(),
        }
# Contacts form
def should_be_empty(value):
    if value:
        raise forms.ValidationError('Feild is not empty')

class ContactForm(forms.Form):
    name = forms.CharField(required = True)
    email =  forms.EmailField(required = True)
    message = forms.CharField(required = True, widget= forms.Textarea(attrs={'rows': 4}))
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave empty", validators=[should_be_empty]
    )

blog/views.py
from django.template.loader import get_template
from django.views import generic
from .models import Post
from .forms import CommentForm, ContactForm
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 3


class AboutView(generic.TemplateView):
    template_name = 'about.html'



def ContactView(request):
    template_name = 'contact.html'
    form = ContactForm()
    flag = None
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'Contact Enquiry from {form.cleaned_data["name"]}'
            message = form.cleaned_data["message"]
            sender = form.cleaned_data["email"]
            recipients = ['shreya.barapatre.consultadd@gmail.com','shreya.s.consultadd@gmail.com']
            try:
                res = send_mail(subject=subject,message=message,from_email= sender, recipient_list=recipients)
                print(res)
                flag = 'Success'
            except BadHeaderError:
                return HttpResponse('Invalid Header found...')
    return render(request , template_name, {'form':form, 'flag':flag})



def post_detail(request, slug):
    template_name = "post_detail.html"
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True).order_by("-created_on")
    new_comment = None
    # Comment posted
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        template_name,
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )

templates/about.html
{% extends 'base.html' %} {% block content %}

<div class="container">
<br><br><br><br>
    <div class="card">
        <div class="card-body">
            <span style="margin: 5%; font-size: 22px">

                    The Blog Central is an ambitious multimedia effort founded in 2020 to examine how technology will change life in the future for a massive mainstream audience.<br><br>
                    Our original editorial insight was that technology had migrated from the far fringes of the culture to the absolute center as mobile technology created a new generation of digital consumers. <br><br>
                    Now, we live in a dazzling world of screens that has ushered in revolutions in media, transportation, and science. <br><br>
                    The future is arriving faster than ever. <br><br>
                    Our mission is to empower the most talented web voices and their audiences.<br><br>
                    Got a tip for us? <a href="{% url 'contact' %}"> Here's how to send it securely.</a><br><br>

            </span>
        </div>


    </div>

</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>




<head>
  <title>Blog Central</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
  <meta name="google" content="notranslate" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

</head>

<body>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light shadow" id="mainNav">
    <div class="container-fluid" style="font-size: 24px">
      <a class="navbar-brand text-black font-weight-bold " href="{% url 'home' %}" style="font-size: 32px">Blog central</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item ">
            <a class="nav-link  text-black font-weight-bold" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
    </div>
  </nav>


  {% block content %}
  <!-- Content Goes here -->
  {% endblock content %}

  <!-- Footer -->
  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Blog Central</p>
  </footer>
  <!-- bootstrap scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>




</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<style>
.container{
    padding-top: 15px;
}
#id_name{
    width: 100%;
}
#id_email{
    width: 100%;
}
#id_message{
    width: 100%;
}
</style>

   <div class="container">
   <br><br><br>
   <div class="row">
        <div class="col-md-6">
           <div class="card">
               <div class="card-header">
                   <h1>Contact Details</h1>
               </div>
               <div class="card-body">
                 <h4>
                    <b> Shreya Barapatre </b>
                 </h4>
                   <p>+91 6264602039 <br>
                   shreyabarapatre@gmail.com</p>
                   <h4>
                    <b> Shreya Soni </b>
                 </h4>
                   <p>+91 8109475570<br>
                   shsoni30@gmail.com</p>
                   <span>
                       <i>
                           Feel free to contact us for any feedback or suggestions...<br>
                           We would ensure fulfilling your requests.
                       </i>
                   </span>
               </div>
           </div>
        </div>
        <div class="col-md-6">
           <div class="card">
               <div class="card-header">
                <h1>Contact Us</h1>
              </div>
               <div class="card-body">
            {% if flag %}
                <div class="alert alert-success" role="alert">
                    Your enquiry has been submitted successfully. We shall respond to it shortly....
                </div>
            {% else %}
               <form method="post" style="margin-top: 1.3em;" action="">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

               {% for field in form.visible_fields %}
               <div class="form-group">
                   {{ field.errors }}
                   <label>{{ field.label_tag }}</label>
                   <p> {{ field }}</p>
               </div>

               {% endfor %}
                <button type="reset" class="btn btn-primary" style="margin-left: 15%">Reset</button>
               <button type="submit" class="btn btn-primary">Submit</button>
               </form>
            {% endif %}
            </div>
            </div>
        </div>
   </div>




   </div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}


<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class=" col-md-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to Blog Central</h3>
          <p class="text-light">We Love Blogs As much as you do..! &nbsp
          </p>
        </div>
      </div>
    </div>
  </div>
  </div>
</header>

<div class="container">
  <div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
      {% for post in post_list %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">{{ post.title  }}</h2>
          <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}}  </p>

          <p class="card-text">{{post.content|slice:":200" | safe}}</p>
          <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
        </div>

      </div>
      {% endfor %}

    </div>
    {% block sidebar %}
    {% include 'sidebar.html' %}
    {% endblock sidebar %}
  </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation conatiner"></nav>
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

  {% endif %}
</ul>
</nav>
</div>
{% endif %}
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comments</h2>

        <p>
          {% endwith %} {% for comment in comments %}
        </p>

        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name | safe}}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on  | safe }}
            </span>
          </p>
          {{ comment.body | safe | linebreaks  }}
        </div>

        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/sidebar.html
{% block sidebar %}



<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This blog central is made on the top of your favourite interests</p>
            <a href="{% url 'about' %}" class="btn btn-danger">Know more!</a>
        </div>
    </div>
</div>

{% endblock sidebar %}